-- CRIA TABELA ASSOCIACAO DE HEROIS

CREATE TABLE assHeroi (
	
	codAH VARCHAR(5),
	nome VARCHAR(25) CONSTRAINT nome_assHeroi NOT NULL,
	CONSTRAINT PK_codAH PRIMARY KEY(codAH)

);


-- CRIA TABELA CIDADE

CREATE TABLE cidade (

	codC VARCHAR(5),
	nome VARCHAR(25) CONSTRAINT nome_cidade NOT NULL,
	CONSTRAINT PK_codC PRIMARY KEY(codC)	

);

-- CRIA TABELA MONSTRO

CREATE TABLE monstro (

	codM VARCHAR(5),
	nome VARCHAR(25) CONSTRAINT nome_monstro NOT NULL,
	CONSTRAINT PK_codM PRIMARY KEY(codM)

);


-- CRIA TABELA BONUS

CREATE TABLE bonus (

	codB VARCHAR(5),
	valor NUMBER(5) CONSTRAINT valor_bonus NOT NULL,
	CONSTRAINT PK_codB PRIMARY KEY(codB)

);


-- CRIA TABELA HEROIS

CREATE TABLE heroi (

	codAH VARCHAR(5),
	rankH VARCHAR(1) CONSTRAINT rank_heroi NOT NULL, 
	nomeH VARCHAR(25) CONSTRAINT nome_heroi NOT NULL,
	CONSTRAINT PK_heroi PRIMARY KEY(codAH,nomeH)

);


-- CRIA TABELA PESSOA

CREATE TABLE pessoa (

	cpf VARCHAR(11),
	nome VARCHAR(25) NOT NULL,
	end_cep VARCHAR(10),
	end_des VARCHAR(50),
	CONSTRAINT PK_cpf PRIMARY KEY(cpf)

);


-- CRIA TABELA TELEFONE

CREATE TABLE pessoaFone(

	cpf VARCHAR(11),
	fone VARCHAR(11) NOT NULL,
	CONSTRAINT PK_fone PRIMARY KEY(cpf,fone),
	CONSTRAINT FK_pessoa FOREIGN KEY(cpf) REFERENCES pessoa(cpf)

);


-- CRIA TABELA CIVIL

CREATE TABLE civil(

	cpf VARCHAR(11),
	CONSTRAINT PK_cpf_civil PRIMARY KEY(cpf),
	CONSTRAINT FK_cpf_civil FOREIGN KEY(cpf) REFERENCES pessoa(cpf)

);


-- CRIA TABELA EXECUTIVO

CREATE TABLE executivo(

	cpf VARCHAR(11),
	cargo VARCHAR(15) NOT NULL,
	codAH VARCHAR(5) NOT NULL,
	codSup VARCHAR(5) NOT NULL,
	CONSTRAINT PK_cpf_exe PRIMARY KEY(cpf),
	CONSTRAINT FK_cpf_exe FOREIGN KEY(cpf) REFERENCES pessoa(cpf),
	CONSTRAINT FK_codAH_exe FOREIGN KEY(codAH) REFERENCES assHeroi(codAH),
	CONSTRAINT FK_codSup_exe FOREIGN KEY(codSup) REFERENCES executivo(cpf)

);
